name: Komodo DeFi Framework (KDF)
slug: kdf-hadex
version: "0.1.4"
description: Runs the Komodo DeFi Framework (kdf) JSON-RPC engine for the HA integration. KDF version is displayed in the add-on logs.
url: https://github.com/smk762/kdf-hadex
startup: services
boot: auto
arch:
  - amd64
init: false
host_network: false
build_from:
  amd64: komodoofficial/komodo-defi-framework:dev-latest

ports:
  7783/tcp: 7783
  8099/tcp: 8099
ports_description:
  7783/tcp: KDF JSON-RPC
  8099/tcp: KDF Ingress Dashboard

map:
  - data:rw
  - share:rw

environment:
  LANG: C.UTF-8

dinghy: false

ingress: true
ingress_port: 8099

panel_icon: mdi:chart-line
panel_title: KDF Trading



options:
  wallet_name: "HAOS KDF Wallet"
  wallet_password: "change_this_password"



schema: 
  wallet_name: str
  wallet_password: password


# https://developers.home-assistant.io/docs/add-ons/configuration/